kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gateway-akka-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: akka-cluster-member
subjects:
- kind: ServiceAccount
  namespace: default
  name: gateway-sa
